DROP TABLE IF EXISTS PERSON;;

CREATE TABLE PERSON(
    id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH VARCHAR(255) NOT NULL,
    PHONE_NUMBER INT
);;